version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: blind_dates_app_development
      DB_USERNAME: root
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blind_dates_app_development
    ports:
      - "5432:5432"
